# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/advisory-schema:ref:refs/tags/v.*
claim_pattern:
  job_workflow_ref: chainguard-dev/advisory-schema/.github/workflows/release.yaml@.*

# the release workflow needs write permissions to push tags
permissions:
  contents: write
