# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: release

on:
  # disabled weekly releases 
  #schedule:
  #  - cron: '0 0 * * 1' # weekly on Monday at 00:00
  workflow_dispatch:
    inputs:
      dry_run:
        description: "dry-run mode: if true, no git tags will be pushed."
        type: boolean
        default: false
      version_bump:
        description: "Version Bump Type"
        required: true
        default: build
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease
          - build
      forced_version:
        description: "(Optional) SemVer2-compliant forced-version to tag explicitly, instead of auto-bumping.
                      Must not already exist"
        required: false
        type: string

permissions: {}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    permissions:
      id-token: write # to inject the OIDC token to octo-sts

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check if any changes since last tag
        id: check
        run: |
          git fetch --tags
          if [ -z "$(git tag --points-at HEAD)" ]; then
            echo "Nothing points at HEAD, bump a new tag"
            echo "bump=yes" >> $GITHUB_OUTPUT
          else
            echo "A tag already points to head, don't bump"
            echo "bump=no" >> $GITHUB_OUTPUT
          fi

      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: release

      - name: Bump and push Git tag
        uses: chainguard-dev/actions/git-tag@f309c81b34d59c103f5b86a2e55a2a647dc8b40a # v1.0.1
        if: steps.check.outputs.bump == 'yes'
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          author: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
          committer: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
          git_tag_prefix: "v"
          bump_level: ${{ inputs.version_bump }}
          dry_run: ${{ inputs.dry_run }}
          forced_version: ${{ inputs.forced_version }}
