# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: release

on:
  schedule:
    - cron: '0 0 * * 2' # weekly on Tuesday at 00:00
  workflow_dispatch:
    inputs:
      dry_run:
        description: "dry-run mode: if true, no git tags will be pushed."
        type: boolean
        default: false
      version_bump:
        description: "Version Bump Type"
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease
          - build
      forced_version:
        description: "(Optional) SemVer2-compliant forced-version to tag explicitly, instead of auto-bumping.
                      Must not already exist"
        required: false
        type: string

permissions: {}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    permissions:
      id-token: write # to inject the OIDC token to octo-sts
      contents: read # to read the repo and tags

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: octo-sts/action@e480437973a6f6ac2e9caa40ecabedc870d76395 # v1.0.1
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: release

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # fetch all history for all branches and tags
          token: ${{ steps.octo-sts.outputs.token }}

      - name: Check if any changes since last tag
        id: check
        run: |
          git fetch --tags
          if [ -z "$(git tag --points-at HEAD)" ]; then
            echo "Nothing points at HEAD, bump a new tag"
            echo "bump=yes" >> $GITHUB_OUTPUT
          else
            echo "A tag already points to head, don't bump"
            echo "bump=no" >> $GITHUB_OUTPUT
          fi

      - name: Bump and push Git tag
        uses: chainguard-dev/actions/git-tag@cd899cc96227b82170571cad1c3d6378d8cba678 # v1.4.15
        if: steps.check.outputs.bump == 'yes'
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          author: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
          committer: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
          git_tag_prefix: "v"
          bump_level: ${{ inputs.version_bump || 'patch' }}
          dry_run: ${{ inputs.dry_run || 'false'}}
          forced_version: ${{ inputs.forced_version || '' }}
